mxm_wifiex: fix build errors
When build wifi driver based on >= Kernel_v5.15.150 Linux code,
will observe the following build errors.

/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_eth_ioctl.c: In function ‘woal_priv_get_ap’:
/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_eth_ioctl.c:5968:39: error: invalid application of ‘sizeof’ to incomplete type ‘char[]’
 5968 |                                 sizeof(mwr->u.ap_addr.sa_data));
      |                                       ^
make[2]: *** [scripts/Makefile.build:252: /work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_eth_ioctl.o] Error 1
make[1]: *** [Makefile:2027: /work/mwifiex/mxm_wifiex/wlan_src] Error 2
make[1]: Leaving directory '/work/linux-nxp-rebase'

This is caused by kernel patch https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.15.y&id=4d3b2bd995ed993756ac43f3bc5be7688e66c8fa
("net: dev: Convert sa_data to flexible array in struct sockaddr"),
now anything using sizeof(sa->sa_data) must switch to sizeof(sa->sa_data_min).

JIRA_ID: SB-23067

Signed-off-by: Prajwal <prajwal.gowda-hm.ext@siemens.com>