rust-crosssdk: Fix: issue when COPYLEFT_LICENSE_INCLUDE is set to *
* When COPYLEFT_LICENSE_INCLUDE is set to * and we try to archive
for sources with all feature added. We get the following error
ERROR: Nothing PROVIDES 'rust-crosssdk-armv8a-glibc'
rust-crosssdk-armv8a-glibc was skipped: We can't extend nativesdk recipes Signed-off-by: Noor Ahsan <noor_ahsan@mentor.com> NOTE: Runtime target 'nativesdk-python3-ndg-httpsclient'
is unbuildable, removing... Missing or unbuildable dependency chain was: ['nativesdk-python3-ndg-httpsclient', 'nativesdk-python3-pyopenssl', 'nativesdk-python3-cryptography',
'virtual/nativesdk-x86_64-oesdk-linux-rust', 'rust-crosssdk-armv8a-glibc']# Please enter the commit message for your changes. Lines starting NOTE: Runtime target
'nativesdk-python3-requests' is unbuildable, removing...# with '#' will be ignored, and an empty message aborts the commit. Missing or unbuildable dependency chain was:
['nativesdk-python3-requests', 'nativesdk-python3-ndg-httpsclient', 'nativesdk-python3-pyopenssl', 'nativesdk-python3-cryptography', 'virtual/nativesdk-x86_64-oesdk-linux-rust',
'rust-crosssdk-armv8a-glibc']# NOTE: Runtime target 'nativesdk-qtinterfaceframework-dev' is unbuildable, removing...# HEAD detached at 74b8142f Missing or unbuildable dependency
chain was: ['nativesdk-qtinterfaceframework-dev', 'nativesdk-python3-qface', 'nativesdk-python3-watchdog', 'nativesdk-python3-requests', 'nativesdk-python3-ndg-httpsclient',
'nativesdk-python3-pyopenssl', 'nativesdk-python3-cryptography', 'virtual/nativesdk-x86_64-oesdk-linux-rust', 'rust-crosssdk-armv8a-glibc']# Changes to be committed: NOTE: Runtime
target 'nativesdk-packagegroup-qt6-toolchain-host' is unbuildable, removing...# new file: meta-sokol-flex-staging/recipes-devtools/rust/rust-crosssdk_1.59.0.bbappend Missing or
unbuildable dependency chain was: ['nativesdk-packagegroup-qt6-toolchain-host', 'nativesdk-qtinterfaceframework-dev', 'nativesdk-python3-qface', 'nativesdk-python3-watchdog',
'nativesdk-python3-requests', 'nativesdk-python3-ndg-httpsclient', 'nativesdk-python3-pyopenssl', 'nativesdk-python3-cryptography', 'virtual/nativesdk-x86_64-oesdk-linux-rust',
'rust-crosssdk-armv8a-glibc']# ERROR: Required build target 'development-image' has no buildable providers.# Untracked files:
Missing or unbuildable dependency chain was: ['development-image', 'buildtools-tarball', 'nativesdk-packagegroup-qt6-toolchain-host', 'nativesdk-qtinterfaceframework-dev',
'nativesdk-python3-qface', 'nativesdk-python3-watchdog', 'nativesdk-python3-requests', 'nativesdk-python3-ndg-httpsclient', 'nativesdk-python3-pyopenssl',
'nativesdk-python3-cryptography', 'virtual/nativesdk-x86_64-oesdk-linux-rust', 'rust-crosssdk-armv8a-glibc']

TUNE_PKGARCH in its PN. crosssdk.bbclass sets TUNE_PKGARCH to SDK_ARCH in an
anonymous python function. I think the fact that there's a delay before it gets
changed causes issues due to PN changing too, especially when combined with
other classes that also use anonymous python functions, like archiver. Changing
it to directly use SDK_ARCH gets past the issue
Set PN as follows
PN:feature-sokol-flex-staging = "rust-crosssdk-${SDK_ARCH}-${RUST_LIBC}"

Signed-off-by: Christopher Larson <chris_larson@mentor.com>
Signed-off-by: Noor Ahsan <noor_ashan@mentor.com>