setup-rh: Make combined script for both RHEL and Rocky host and update accordingly
Enabling required repo's to get install rpcgen package

And due to lower make and python version we are unable to make build succesful so installing required version and creating symbolic link

JIRA ID: SB-23264

We were facing following issues so through this script we have resolved these issues.

1) Due to lower make version so we get following error during bitbake.

ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    make version 4.2.1 is known to have issues on Centos/OpenSUSE and other non-Ubuntu systems. Please use a buildtools-make-tarball or a newer
    version of make.

2) We get following warning due to lower python version.

/usr/lib64/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)

Signed-off-by: Ashish Jain <Ashish_Jain2@mentor.com>