lttng-tools: fix error when multilibs isn't enabled
Fixes a python traceback and AttributeError when `MULTILIBS` is None:

    __anon_22__var_jenkins_workspace_mel_ginkgo_async1_main_incremental_buildtype_mel_label_flex_u22_machine_imx8mpevk_flex_repotop_meta_sokol_flex_meta_sokol_flex_staging_recipes_kernel_lttng_lttng_tools___bbappend
    0001:python () {
    *** 0002:    if not d.getVar('MULTILIBS').strip():
    0003:        return
    0004:
    0005:    variants = (d.getVar("MULTILIB_VARIANTS") or "").split()
    0006:    if 'lib32' in variants:
    Exception: AttributeError: 'NoneType' object has no attribute 'strip'

JIRA: SB-22623

Signed-off-by: Christopher Larson <chris_larson@mentor.com>