pidgin: Create empty pidgin package to serve pidgin-dev dependency
* Yocto SDK build failed when we add iot layer and feature with following error
  ERROR: development-image-1.0-r0 do_populate_sdk: Unable to install packages ...
  Solver encountered 1 problem(s):
  Problem 1/1:
    - conflicting requests
    - nothing provides pidgin = 2.14.2-r0.1 needed by pidgin-dev-2.14.2-r0.1.riscv64

  Solution 1:
    - do not ask to install a package providing pidgin-dev
 The error occured because pidgin package was not being created. All the files
 which were added to this package were already part of other packages. Nothing
 left to be added in pidgin package. Created empty package by setting ALLOW_EMPTY
 variable to satisfy this dependency.

Signed-off-by: Noor Ahsan <noor_ahsan@mentor.com>